import os
import argparse
import subprocess
import sys
import venv
from pathlib import Path

ROOT = Path(__file__).resolve().parent
VENV_DIR = ROOT / ".venv"
REQUIREMENTS_DIR = ROOT / "requirements"
LOCK_FILE = ROOT / "requirements-lock.txt"
REQUIRED_PYTHON = (3, 11)


def run(cmd: list[str], cwd: Path | None = None, *, env: dict[str, str] | None = None) -> subprocess.CompletedProcess[str]:
    print("$", " ".join(str(part) for part in cmd))
    return subprocess.run(cmd, cwd=str(cwd or ROOT), env=env, text=True, capture_output=True)


def get_venv_python() -> Path:
    if os.name == "nt":
        return VENV_DIR / "Scripts" / "python.exe"
    return VENV_DIR / "bin" / "python"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Create or reuse .venv, install requirements, and write requirements-lock.txt. "
            "Use --update-libraries to upgrade dependency versions in the environment."
        )
    )
    parser.add_argument(
        "--update-libraries",
        action="store_true",
        help="Upgrade packages when installing requirements files.",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()

    if sys.version_info[:2] != REQUIRED_PYTHON:
        detected = f"{sys.version_info.major}.{sys.version_info.minor}.{sys.version_info.micro}"
        print(
            f"Python 3.11 is required to match the Docker runtime images; found {detected}. "
            "Install Python 3.11 and run this script with that interpreter.",
            file=sys.stderr,
        )
        return 1

    venv_python = get_venv_python()

    if not VENV_DIR.exists():
        print(f"Creating virtual environment at {VENV_DIR}")
        # Do not upgrade bootstrap tooling implicitly; dependency versions are
        # captured after installation in the repository-level lock file.
        venv.EnvBuilder(with_pip=True).create(VENV_DIR)

    if not venv_python.exists():
        print(f"Virtual environment Python was not created at {venv_python}", file=sys.stderr)
        return 1

    requirements_files = [
        REQUIREMENTS_DIR / "ui.txt",
        REQUIREMENTS_DIR / "notebook.txt",
        REQUIREMENTS_DIR / "docs.txt",
        REQUIREMENTS_DIR / "airflow.txt",
        REQUIREMENTS_DIR / "spark.txt",
    ]

    failures: list[Path] = []
    for req_file in requirements_files:
        if not req_file.exists():
            print(f"Skipping missing requirement file: {req_file}")
            continue

        print(f"\nInstalling {req_file.relative_to(ROOT)}")
        pip_install_cmd = [str(venv_python), "-m", "pip", "install", "-r", str(req_file)]
        if args.update_libraries:
            pip_install_cmd.insert(-2, "--upgrade")
        result = run(pip_install_cmd)
        if result.stdout:
            print(result.stdout)
        if result.stderr:
            print(result.stderr, file=sys.stderr)

        if result.returncode != 0:
            failures.append(req_file)
            print(f"Installation failed for {req_file.relative_to(ROOT)}")

    if failures:
        print("\nDependency installation failed; no lock file was generated.", file=sys.stderr)
        for req_file in failures:
            print(f" - {req_file.relative_to(ROOT)}", file=sys.stderr)
        return 1

    # ``pip freeze --all`` records direct and transitive packages for this exact
    # Python 3.11 environment. Commit the output after a reviewed dependency
    # update; it is the reproducible reference for host-side tooling.
    lock_result = run([str(venv_python), "-m", "pip", "freeze", "--all"])
    if lock_result.returncode != 0:
        print(lock_result.stderr, file=sys.stderr)
        return lock_result.returncode
    LOCK_FILE.write_text(
        "# Generated by setup_venv.py with Python 3.11. Do not edit manually.\n"
        "# Run `py -3.11 setup_venv.py --update-libraries` to upgrade packages and refresh this lock.\n"
        + lock_result.stdout,
        encoding="utf-8",
    )
    print(f"\nWrote resolved dependency lock file: {LOCK_FILE.relative_to(ROOT)}")

    print("\nVirtual environment is ready.")
    activation_path = VENV_DIR / ("Scripts" if os.name == "nt" else "bin")
    print(f"Activate it with: {activation_path / 'activate'}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
